version: '3'

networks:
  backend:
    driver: bridge

services:
  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    # env_file:
    #   - .env
    image: nestjs-image
    volumes:
      - .:/home/node
    environment:
      - API_PORT=3000
    ports:
      - 3000:3000
    depends_on:
      - postgresql
    networks:
      - backend

  postgresql:
    image: docker.io/bitnami/postgresql:16
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_DATABASE=nestjs
      - POSTGRESQL_USERNAME=nestjs
      - POSTGRESQL_PASSWORD=password
    networks:
      - backend

  # redis-node-0:
  #   image: docker.io/bitnami/redis-cluster:7.2
  #   volumes:
  #     - redis-cluster_data-0:/bitnami/redis/data
  #   environment:
  #     - 'REDIS_PASSWORD=bitnami'
  #     - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
  #   networks:
  #     - backend

  # redis-node-1:
  #   image: docker.io/bitnami/redis-cluster:7.2
  #   volumes:
  #     - redis-cluster_data-1:/bitnami/redis/data
  #   environment:
  #     - 'REDIS_PASSWORD=bitnami'
  #     - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
  #   networks:
  #     - backend

  # redis-node-2:
  #   image: docker.io/bitnami/redis-cluster:7.2
  #   volumes:
  #     - redis-cluster_data-2:/bitnami/redis/data
  #   environment:
  #     - 'REDIS_PASSWORD=bitnami'
  #     - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
  #   networks:
  #     - backend
  # redis-node-3:
  #   image: docker.io/bitnami/redis-cluster:7.2
  #   volumes:
  #     - redis-cluster_data-3:/bitnami/redis/data
  #   environment:
  #     - 'REDIS_PASSWORD=bitnami'
  #     - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
  #   networks:
  #     - backend

  # redis-node-4:
  #   image: docker.io/bitnami/redis-cluster:7.2
  #   volumes:
  #     - redis-cluster_data-4:/bitnami/redis/data
  #   environment:
  #     - 'REDIS_PASSWORD=bitnami'
  #     - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
  #   networks:
  #     - backend

  # redis-node-5:
  #   image: docker.io/bitnami/redis-cluster:7.2
  #   volumes:
  #     - redis-cluster_data-5:/bitnami/redis/data
  #   depends_on:
  #     - redis-node-0
  #     - redis-node-1
  #     - redis-node-2
  #     - redis-node-3
  #     - redis-node-4
  #   environment:
  #     - 'REDIS_PASSWORD=bitnami'
  #     - 'REDISCLI_AUTH=bitnami'
  #     - 'REDIS_CLUSTER_REPLICAS=1'
  #     - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
  #     - 'REDIS_CLUSTER_CREATOR=yes'
  #   networks:
  #     - backend

volumes:
  redis-cluster_data-0:
    driver: local
  redis-cluster_data-1:
    driver: local
  redis-cluster_data-2:
    driver: local
  redis-cluster_data-3:
    driver: local
  redis-cluster_data-4:
    driver: local
  redis-cluster_data-5:
    driver: local
  postgresql_data:
    driver: local